version: '3'
services:
  jupyter:
    build:
      context: .
    volumes:
      - ./notebooks:/notebooks
      - ./config/jupyterlab-code-formatter.json:/home/jovyan/.jupyter/lab/user-settings/jupyterlab_code_formatter/settings.jupyterlab-settings
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    env_file:
      - .env
